# Generated by Django 2.0.5 on 2018-05-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'Mcq'), ('subjective', 'Subjective'), ('fill in the blanks', 'Fb'), ('true or false', 'Tf'), ('match the following', 'Match')], max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Grade'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Subject'),
        ),
    ]
