# Generated by Django 2.0.5 on 2018-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0003_auto_20180518_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('short', 'short answer'), ('long', 'long answer'), ('fb', 'fill in the blanks'), ('Tf', 'true or false'), ('Match', 'match the following')], max_length=50),
        ),
    ]
