# Generated by Django 2.0.5 on 2018-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0007_auto_20180521_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
