# Generated by Django 2.0.5 on 2018-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0010_auto_20180523_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='match'),
        ),
    ]
