# Generated by Django 2.0.5 on 2018-05-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0011_auto_20180523_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qp_generator.School'),
            preserve_default=False,
        ),
    ]
