# Generated by Django 2.0.5 on 2018-05-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0012_question_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qp_generator.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='max_grade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
