# Generated by Django 2.0.5 on 2018-06-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0013_auto_20180524_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=200)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qp_generator.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
