# Generated by Django 2.0.5 on 2018-06-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0014_auto_20180604_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qp_generator.School'),
            preserve_default=False,
        ),
    ]
