# Generated by Django 2.0.5 on 2018-06-12 04:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0015_paper_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='paper',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 4, 30, 16, 565041, tzinfo=utc), verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='200*50 is recommended', null=True, upload_to='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('short', 'short answer'), ('long', 'long answer'), ('fb', 'fill in the blanks'), ('Tf', 'true or false'), ('Match', 'match the following')], max_length=50),
        ),
    ]
