# Generated by Django 2.0.5 on 2018-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_generator', '0019_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(default='password123', max_length=100),
            preserve_default=False,
        ),
    ]
